name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Match your project's Node version
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint
    - name: Run unit and integration tests
      run: npm test -- --coverage # If you want coverage reports
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/ # Default output directory for Vitest coverage

  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint-and-unit-tests # Run after unit tests pass
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start Next.js app
      run: npm run dev & # Run in background
    - name: Wait for Next.js app to be ready
      run: npx wait-on http://localhost:3000
    - name: Run Playwright tests
      run: npm run test:e2e
    - uses: actions/upload-artifact@v4
      if: always() # Upload report even if tests fail
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
