name: Manual E2E Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  run-e2e-only:
    permissions:
      pull-requests: write
      issues: write
      checks: write
    # This calls the same logic, but with no dependencies
    uses: ./.github/workflows/e2e.yml
